'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Messages
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ChessMessaging.Messages", GetType(Messages).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Insert move: &quot;%1&quot;, as %2th subvariant ?.
        '''</summary>
        Friend Shared ReadOnly Property AddNewSubVariant() As String
            Get
                Return ResourceManager.GetString("AddNewSubVariant", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add %1.
        '''</summary>
        Friend Shared ReadOnly Property AddPiece() As String
            Get
                Return ResourceManager.GetString("AddPiece", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add text.
        '''</summary>
        Friend Shared ReadOnly Property AddText() As String
            Get
                Return ResourceManager.GetString("AddText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File &quot;%1&quot; already exists in &quot;%2&quot; !  Do you want to overwrite the existing file ?.
        '''</summary>
        Friend Shared ReadOnly Property AlreadyExists() As String
            Get
                Return ResourceManager.GetString("AlreadyExists", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are You Sure ?.
        '''</summary>
        Friend Shared ReadOnly Property Are_You_Sure() As String
            Get
                Return ResourceManager.GetString("Are You Sure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Better capture two-fold-attacked-piece at %1 with %2 at %3.
        '''</summary>
        Friend Shared ReadOnly Property CaptureWithLowerPiece() As String
            Get
                Return ResourceManager.GetString("CaptureWithLowerPiece", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Missed checkmate in 2 by %1 and %2.
        '''</summary>
        Friend Shared ReadOnly Property CheckMateIn2() As String
            Get
                Return ResourceManager.GetString("CheckMateIn2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Opponent can checkmate using %1.
        '''</summary>
        Friend Shared ReadOnly Property CheckMateOpponent() As String
            Get
                Return ResourceManager.GetString("CheckMateOpponent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Column &quot;%1&quot;, or Row &quot;%2&quot; out of range (Has to be be 1 to 8).
        '''</summary>
        Friend Shared ReadOnly Property ColumnRowRange() As String
            Get
                Return ResourceManager.GetString("ColumnRowRange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Comment (after).
        '''</summary>
        Friend Shared ReadOnly Property CommentAfter() As String
            Get
                Return ResourceManager.GetString("CommentAfter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Comment (before).
        '''</summary>
        Friend Shared ReadOnly Property CommentBefore() As String
            Get
                Return ResourceManager.GetString("CommentBefore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CommentAfter is not empty&quot;%1&quot;.
        '''</summary>
        Friend Shared ReadOnly Property CommentNotEmpty() As String
            Get
                Return ResourceManager.GetString("CommentNotEmpty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Well done !  The answer %1 is correct.
        '''</summary>
        Friend Shared ReadOnly Property CorrectAnswer() As String
            Get
                Return ResourceManager.GetString("CorrectAnswer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pinning of %1 could hav been solved by %2.
        '''</summary>
        Friend Shared ReadOnly Property DefendAgainstPinning() As String
            Get
                Return ResourceManager.GetString("DefendAgainstPinning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete all moves and add move &quot;%1&quot; ?.
        '''</summary>
        Friend Shared ReadOnly Property DeleteAllMoves() As String
            Get
                Return ResourceManager.GetString("DeleteAllMoves", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete arrow from %1 to %2.
        '''</summary>
        Friend Shared ReadOnly Property DeleteArrow() As String
            Get
                Return ResourceManager.GetString("DeleteArrow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete marker at %1.
        '''</summary>
        Friend Shared ReadOnly Property DeleteMarker() As String
            Get
                Return ResourceManager.GetString("DeleteMarker", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete move &quot;%1&quot; and subsequent moves ?.
        '''</summary>
        Friend Shared ReadOnly Property DeleteMove() As String
            Get
                Return ResourceManager.GetString("DeleteMove", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete %1.
        '''</summary>
        Friend Shared ReadOnly Property DeletePiece() As String
            Get
                Return ResourceManager.GetString("DeletePiece", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete text &quot;%1&quot; from %2.
        '''</summary>
        Friend Shared ReadOnly Property DeleteText() As String
            Get
                Return ResourceManager.GetString("DeleteText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Using %1 defender %2 of %3 could be eliminated.
        '''</summary>
        Friend Shared ReadOnly Property EliminateDefence() As String
            Get
                Return ResourceManager.GetString("EliminateDefence", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to %1 is (still) in check after the move.
        '''</summary>
        Friend Shared ReadOnly Property InCheckAfterMove() As String
            Get
                Return ResourceManager.GetString("InCheckAfterMove", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The answer %1 is incorrect. Please try again.
        '''</summary>
        Friend Shared ReadOnly Property IncorrectAnswer() As String
            Get
                Return ResourceManager.GetString("IncorrectAnswer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The answer %1 isn&apos;t quite correct.  Please try again.  Total score increased by %2 points.
        '''</summary>
        Friend Shared ReadOnly Property IncorrectAnswer2() As String
            Get
                Return ResourceManager.GetString("IncorrectAnswer2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Initial position of %1 is incorrect.
        '''</summary>
        Friend Shared ReadOnly Property IncorrectInitPos() As String
            Get
                Return ResourceManager.GetString("IncorrectInitPos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Insert move &quot;%1&quot;, and delete all subsequent moves ?.
        '''</summary>
        Friend Shared ReadOnly Property InsertMove() As String
            Get
                Return ResourceManager.GetString("InsertMove", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Insert move &quot;%1&quot;, as a new subvariant ?.
        '''</summary>
        Friend Shared ReadOnly Property InsertSubVariant() As String
            Get
                Return ResourceManager.GetString("InsertSubVariant", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to King was moved 2 places; Assumed castling is intended.
        '''</summary>
        Friend Shared ReadOnly Property IntendedCastling() As String
            Get
                Return ResourceManager.GetString("IntendedCastling", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid arrow list format at PGN.
        '''</summary>
        Friend Shared ReadOnly Property InvalidArrowList() As String
            Get
                Return ResourceManager.GetString("InvalidArrowList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid castling; King in check before or after move.
        '''</summary>
        Friend Shared ReadOnly Property InvalidCastling1() As String
            Get
                Return ResourceManager.GetString("InvalidCastling1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid castling; King in check during the move.
        '''</summary>
        Friend Shared ReadOnly Property InvalidCastling2() As String
            Get
                Return ResourceManager.GetString("InvalidCastling2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid castling; A piece was standing at %1.
        '''</summary>
        Friend Shared ReadOnly Property InvalidCastling3() As String
            Get
                Return ResourceManager.GetString("InvalidCastling3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid castling; King was not at intial position.
        '''</summary>
        Friend Shared ReadOnly Property InvalidCastling4() As String
            Get
                Return ResourceManager.GetString("InvalidCastling4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid castling on the King&apos;s side; A piece was standing at %1.
        '''</summary>
        Friend Shared ReadOnly Property InvalidCastling5() As String
            Get
                Return ResourceManager.GetString("InvalidCastling5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid castling on the Queen&apos;s side; A piece was standing at %1.
        '''</summary>
        Friend Shared ReadOnly Property InvalidCastling6() As String
            Get
                Return ResourceManager.GetString("InvalidCastling6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid castling on the Queen&apos;s side; King doesn&apos;t go to the right field.
        '''</summary>
        Friend Shared ReadOnly Property InvalidCastling6b() As String
            Get
                Return ResourceManager.GetString("InvalidCastling6b", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid castling; King doesn&apos;t go to the right field.
        '''</summary>
        Friend Shared ReadOnly Property InvalidCastling7() As String
            Get
                Return ResourceManager.GetString("InvalidCastling7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid castling on the King&apos;s side; Pieces were moved.
        '''</summary>
        Friend Shared ReadOnly Property InvalidCastling8() As String
            Get
                Return ResourceManager.GetString("InvalidCastling8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid castling on the Queen&apos;s side; Pieces were moved.
        '''</summary>
        Friend Shared ReadOnly Property InvalidCastling9() As String
            Get
                Return ResourceManager.GetString("InvalidCastling9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Color &quot;%1&quot; is invalid. Should be &quot;R&quot;, &quot;G&quot;, &quot;Y&quot;, &quot;B&quot;, &quot;C&quot; or &quot;O&quot;.
        '''</summary>
        Friend Shared ReadOnly Property InvalidColor() As String
            Get
                Return ResourceManager.GetString("InvalidColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Piece &quot;%1&quot; in FEN.
        '''</summary>
        Friend Shared ReadOnly Property InvalidFENPiece() As String
            Get
                Return ResourceManager.GetString("InvalidFENPiece", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Field name &quot;%1&quot; is invalid. Should be &quot;a1&quot; thru &quot;h8&quot;.
        '''</summary>
        Friend Shared ReadOnly Property InvalidFieldName() As String
            Get
                Return ResourceManager.GetString("InvalidFieldName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The specified name &quot;%1&quot; is not defined as a standard Icon.
        '''</summary>
        Friend Shared ReadOnly Property InvalidIconName() As String
            Get
                Return ResourceManager.GetString("InvalidIconName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The specified name &quot;%1&quot; is not defined as a standard Image.
        '''</summary>
        Friend Shared ReadOnly Property InvalidImageName() As String
            Get
                Return ResourceManager.GetString("InvalidImageName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid marker list format at PGN.
        '''</summary>
        Friend Shared ReadOnly Property InvalidMarerkList() As String
            Get
                Return ResourceManager.GetString("InvalidMarerkList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid move for a %1.
        '''</summary>
        Friend Shared ReadOnly Property InvalidMove() As String
            Get
                Return ResourceManager.GetString("InvalidMove", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Code &quot;%1&quot; is invalid. Should be a &quot;$&quot; with valid NAG number.
        '''</summary>
        Friend Shared ReadOnly Property InvalidNAGCode() As String
            Get
                Return ResourceManager.GetString("InvalidNAGCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Piece &quot;%1&quot;.
        '''</summary>
        Friend Shared ReadOnly Property InvalidPiece() As String
            Get
                Return ResourceManager.GetString("InvalidPiece", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid training question format at PGN.
        '''</summary>
        Friend Shared ReadOnly Property InvalidQuestion() As String
            Get
                Return ResourceManager.GetString("InvalidQuestion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Symbol &quot;%1&quot; is invalid. Should be &quot;R&quot;, &quot;G&quot;, &quot;Y&quot;, &quot;B&quot;, &quot;C&quot;, &quot;O&quot;, &quot;+&quot;, &quot;-&quot;, &quot;0&quot;, &quot;#&quot;, &quot;.&quot; or &quot;*&quot;.
        '''</summary>
        Friend Shared ReadOnly Property InvalidSymbol() As String
            Get
                Return ResourceManager.GetString("InvalidSymbol", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid text list format at PGN.
        '''</summary>
        Friend Shared ReadOnly Property InvalidTextList() As String
            Get
                Return ResourceManager.GetString("InvalidTextList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The move &quot;%1&quot; is invalid. Should be in the format &quot;x9x9&quot; specifying from field and to field.
        '''</summary>
        Friend Shared ReadOnly Property InvalidTQUMove() As String
            Get
                Return ResourceManager.GetString("InvalidTQUMove", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Current move is not part of a variant.
        '''</summary>
        Friend Shared ReadOnly Property InvalidVariantMove() As String
            Get
                Return ResourceManager.GetString("InvalidVariantMove", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to King not yet at a safe position.
        '''</summary>
        Friend Shared ReadOnly Property KingNotSafe() As String
            Get
                Return ResourceManager.GetString("KingNotSafe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Message text with key &quot;%1&quot;  not found.
        '''</summary>
        Friend Shared ReadOnly Property MessageNotFound() As String
            Get
                Return ResourceManager.GetString("MessageNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Missed attack on a pinned piece %1.
        '''</summary>
        Friend Shared ReadOnly Property MissedAttackOnPinnedPiece() As String
            Get
                Return ResourceManager.GetString("MissedAttackOnPinnedPiece", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Missed discovered attack %1. Head-piece %2 could attack %3 and tail-piece &amp;4 could attack %5.
        '''</summary>
        Friend Shared ReadOnly Property MissedDiscoverdAttack() As String
            Get
                Return ResourceManager.GetString("MissedDiscoverdAttack", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Missed discovered check by %1.
        '''</summary>
        Friend Shared ReadOnly Property MissedDiscoveredCheck() As String
            Get
                Return ResourceManager.GetString("MissedDiscoveredCheck", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Missed double attack on %2 and %3 after %1.
        '''</summary>
        Friend Shared ReadOnly Property MissedDoubleAttack() As String
            Get
                Return ResourceManager.GetString("MissedDoubleAttack", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Double check by %1 would have been better.
        '''</summary>
        Friend Shared ReadOnly Property MissedDoubleCheck() As String
            Get
                Return ResourceManager.GetString("MissedDoubleCheck", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to %1 would have been checkmate.
        '''</summary>
        Friend Shared ReadOnly Property MissedMateIn1() As String
            Get
                Return ResourceManager.GetString("MissedMateIn1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Missed multiple attack on %2, %3, %4,... after %1.
        '''</summary>
        Friend Shared ReadOnly Property MissedMultiAttack() As String
            Get
                Return ResourceManager.GetString("MissedMultiAttack", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pinned piece at %1 is a bad defender, so %2 would have been possible.
        '''</summary>
        Friend Shared ReadOnly Property MissedPinnedPieceIsBadDefender() As String
            Get
                Return ResourceManager.GetString("MissedPinnedPieceIsBadDefender", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Could pin piece at %1 with move %2.
        '''</summary>
        Friend Shared ReadOnly Property MissedPinning() As String
            Get
                Return ResourceManager.GetString("MissedPinning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Profitable exchange at %1.
        '''</summary>
        Friend Shared ReadOnly Property MissedProfitExchange() As String
            Get
                Return ResourceManager.GetString("MissedProfitExchange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Missed triple attack on %2, %3 and %4 after %1.
        '''</summary>
        Friend Shared ReadOnly Property MissedTripleAttack() As String
            Get
                Return ResourceManager.GetString("MissedTripleAttack", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Could capture a twice attacked piece at %1.
        '''</summary>
        Friend Shared ReadOnly Property MissedTwoFoldAttack() As String
            Get
                Return ResourceManager.GetString("MissedTwoFoldAttack", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Could capture an uncovered piece at %1.
        '''</summary>
        Friend Shared ReadOnly Property MissedUncoverdedPiece() As String
            Get
                Return ResourceManager.GetString("MissedUncoverdedPiece", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Missing space to divide &quot;%1&quot; into parts !.
        '''</summary>
        Friend Shared ReadOnly Property MissingSpace() As String
            Get
                Return ResourceManager.GetString("MissingSpace", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Before Or After not recoginized: &quot;%1&quot;.
        '''</summary>
        Friend Shared ReadOnly Property NAGBeforeOrAfter() As String
            Get
                Return ResourceManager.GetString("NAGBeforeOrAfter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No pawn at the center.
        '''</summary>
        Friend Shared ReadOnly Property NoPawnAtCenter() As String
            Get
                Return ResourceManager.GetString("NoPawnAtCenter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No Space found at &quot;%1&quot;.
        '''</summary>
        Friend Shared ReadOnly Property NoSpaceFound() As String
            Get
                Return ResourceManager.GetString("NoSpaceFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Uncovered piece at %1.
        '''</summary>
        Friend Shared ReadOnly Property NotCoverded() As String
            Get
                Return ResourceManager.GetString("NotCoverded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Opponent now has a profitable exchange at %1 with the %2.
        '''</summary>
        Friend Shared ReadOnly Property OfferingPieces() As String
            Get
                Return ResourceManager.GetString("OfferingPieces", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Opponent can capture the isufficiently defended %2 at %1.
        '''</summary>
        Friend Shared ReadOnly Property OfferingPieces2() As String
            Get
                Return ResourceManager.GetString("OfferingPieces2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open PGN File.
        '''</summary>
        Friend Shared ReadOnly Property OpenPGNFile() As String
            Get
                Return ResourceManager.GetString("OpenPGNFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PGN was not specific enough for Piece &quot;%1&quot; moving to &quot;%2&quot;.
        '''</summary>
        Friend Shared ReadOnly Property PGNMoveInvalid() As String
            Get
                Return ResourceManager.GetString("PGNMoveInvalid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Play.
        '''</summary>
        Friend Shared ReadOnly Property Play() As String
            Get
                Return ResourceManager.GetString("Play", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Position after: %1.
        '''</summary>
        Friend Shared ReadOnly Property Position_After() As String
            Get
                Return ResourceManager.GetString("Position After", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Position before: %1.
        '''</summary>
        Friend Shared ReadOnly Property Position_Before() As String
            Get
                Return ResourceManager.GetString("Position Before", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sorry, but something went really wrong....
        '''</summary>
        Friend Shared ReadOnly Property ReallyWrong() As String
            Get
                Return ResourceManager.GetString("ReallyWrong", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Redo empty.
        '''</summary>
        Friend Shared ReadOnly Property RedoEmpty() As String
            Get
                Return ResourceManager.GetString("RedoEmpty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Redo of changes:&quot;%1&quot;.
        '''</summary>
        Friend Shared ReadOnly Property RedoTooltipText() As String
            Get
                Return ResourceManager.GetString("RedoTooltipText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rooks not yet connected.
        '''</summary>
        Friend Shared ReadOnly Property RooksNotConnected() As String
            Get
                Return ResourceManager.GetString("RooksNotConnected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Twice or more moves of the same color; Save anyhow ?.
        '''</summary>
        Friend Shared ReadOnly Property SameColor() As String
            Get
                Return ResourceManager.GetString("SameColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to %1 has moved twice.
        '''</summary>
        Friend Shared ReadOnly Property SameColorTwice() As String
            Get
                Return ResourceManager.GetString("SameColorTwice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Current (PGN/XPGN)-file has been changed !  Save current file first ?.
        '''</summary>
        Friend Shared ReadOnly Property SaveChanges() As String
            Get
                Return ResourceManager.GetString("SaveChanges", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Setup.
        '''</summary>
        Friend Shared ReadOnly Property Setup() As String
            Get
                Return ResourceManager.GetString("Setup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Starting position.
        '''</summary>
        Friend Shared ReadOnly Property Starting_Position() As String
            Get
                Return ResourceManager.GetString("Starting Position", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unforseen condition with a piece named: &quot;%1&quot;.
        '''</summary>
        Friend Shared ReadOnly Property StrangePiece() As String
            Get
                Return ResourceManager.GetString("StrangePiece", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The game contains one or more training questions.  Switch to TRAINING mode ?.
        '''</summary>
        Friend Shared ReadOnly Property SwitchToTraining() As String
            Get
                Return ResourceManager.GetString("SwitchToTraining", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There is a threat of an unprofitable exchange at %1.
        '''</summary>
        Friend Shared ReadOnly Property ThreatUnprofitExchange() As String
            Get
                Return ResourceManager.GetString("ThreatUnprofitExchange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Training.
        '''</summary>
        Friend Shared ReadOnly Property Training() As String
            Get
                Return ResourceManager.GetString("Training", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to What is the best move ?.
        '''</summary>
        Friend Shared ReadOnly Property TrainingQuestion() As String
            Get
                Return ResourceManager.GetString("TrainingQuestion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Twice attacked piece at %1.
        '''</summary>
        Friend Shared ReadOnly Property TwoFoldAttacked() As String
            Get
                Return ResourceManager.GetString("TwoFoldAttacked", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to %1 Pieces are not yet developed.
        '''</summary>
        Friend Shared ReadOnly Property UndevelopedPieces() As String
            Get
                Return ResourceManager.GetString("UndevelopedPieces", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Undo empty.
        '''</summary>
        Friend Shared ReadOnly Property UndoEmpty() As String
            Get
                Return ResourceManager.GetString("UndoEmpty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Undo of changes: &quot;%1&quot;.
        '''</summary>
        Friend Shared ReadOnly Property UndoTooltipText() As String
            Get
                Return ResourceManager.GetString("UndoTooltipText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unknown NAG: &quot;%1&quot;.
        '''</summary>
        Friend Shared ReadOnly Property UnknownNAG() As String
            Get
                Return ResourceManager.GetString("UnknownNAG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unkown Language specified to store.
        '''</summary>
        Friend Shared ReadOnly Property UnkownLanguage() As String
            Get
                Return ResourceManager.GetString("UnkownLanguage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unprofitable exchange at %1.
        '''</summary>
        Friend Shared ReadOnly Property UnprofitExchange() As String
            Get
                Return ResourceManager.GetString("UnprofitExchange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unprofitable capture at %2. The %1 at %2 is %3 times attacked, but also %4 times defended.
        '''</summary>
        Friend Shared ReadOnly Property UnprofitTwoFoldCapture() As String
            Get
                Return ResourceManager.GetString("UnprofitTwoFoldCapture", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete all moves and update the initial position ?.
        '''</summary>
        Friend Shared ReadOnly Property UpdateFEN() As String
            Get
                Return ResourceManager.GetString("UpdateFEN", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
